import java.io.File;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Map;
import java.util.Scanner;
import java.util.function.Function;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/**
 * Subword finder
 * @author marin
 * @ version 2023 -02 - 09
 */
public class SubWordFinder implements WordFinder{
    private ArrayList<ArrayList<String>> dictionary;
    private String alpha = "abcdefghijklmnopqrstuvwxyz";

    /**
     * constructor method for dictionary
     * creates all our ole buckets
     */
    public SubWordFinder(){
        dictionary = new ArrayList<>();
        for(int i = 0; i < 26; i++){
            dictionary.add(new ArrayList<String>());
        }
        //System.out.println("DEBUG LINE 23 " + dictionary.size());
        populateDictionary();
    }



    private int binarySearch(ArrayList<String> arrayLost, int left, int right, String word)
    {
        if (left <= right) {
            int mid = (right + left) / 2;
            if (arrayLost.get(mid).equals(word))
                return mid;
            //else if(word.compareTo(arrayLost.get(mid)) < 0)
                //return binarySearch(arrayLost, mid+1, right, word);
            //else
                //return binarySearch(arrayLost, left, mid-1, word);
            return word.compareTo(arrayLost.get(mid)) > 0 ? binarySearch(arrayLost, mid + 1, right, word) : binarySearch(arrayLost, left, mid - 1, word);
        }

        // We reach here when element is not present
        // in array
        return -1;
    }
    @Override
    /**
     * Method to populate the database from the text file, and sort each of the buckets lexicographically
     */
    public void  populateDictionary() {
        try{
            Scanner in = new Scanner(new File("new_scrabble.txt"));
            //Scanner in = new Scanner(new File("words_all_os.txt"));
            String word;
            while(in.hasNext()){
                word = in.nextLine();
                //System.out.println("DEBUG: " + word);
                //System.out.println("DEBUG: " + alpha.indexOf(word.substring(0,1)));
                dictionary.get(alpha.indexOf(word.substring(0,1))).add(word);
            }
            in.close();
            for(int i = 0; i < dictionary.size(); i++){
                Collections.sort(dictionary.get(i));
            }
            //for(ArrayList<String> bucket : dictionary)
            //System.out.println(bucket);
        }
        catch(Exception e){
            System.out.println("HEYHEYHEYHEY: " + e);
            e.printStackTrace();
        }
    }

    @Override
    /**
     * Parse all the subwords and populate an arraylist with subword objects
     * @returns ArrayList subwords
     */
    public ArrayList<SubWord> getSubWords() {
        ArrayList<SubWord> subwords = new ArrayList<>();

        //System.out.println("DEBUG: " + dictionary.size());
        //String[] subs;
        for(ArrayList<String> bucket : dictionary) {
            //System.out.println("DEBUG: " + bucket.get(1).substring(0, 1) + " = " + bucket.size());
            for (String word : bucket) {
                String front, back;
                for (int i = 2; i < word.length() - 1; i++) {
                    front = word.substring(0, i);
                    back = word.substring(i);
                    //System.out.println(subs[0] + " " + subs [1] + " " + inDictionary(subs[0]) + " " + inDictionary(subs[1]));
                    if (inDictionary(front) && inDictionary(back)) {
                        subwords.add(new SubWord(word, front, back));
                    }
                }
            }
        }



        //System.out.println("DEBUG line 95: " + subwords.size());
        return subwords;
    }

    @Override
    /**
     * uses binarysearch to see if word is in database
     * @param word word to find
     * @returns inDictionary if the word is in dictionary
     */
    public boolean inDictionary(String word) {

        //return binarySearch(dictionary.get(word.indexOf(word.substring(0,1))), 0, dictionary.get(word.indexOf(word.substring(0,1))).size(), word ) >=0;

        ArrayList<String> bucket = dictionary.get(alpha.indexOf(word.substring(0,1)));
        return binarySearch(bucket, 0, bucket.size()-1, word) >= 0;
        //return Collections.binarySearch(bucket, word) >= 0;
    }

    /**
     * Prints out all the stuff
     * @param args
     * has this stupid copy-paste code for extra credit
     */
    public static void main(String[] args) {
        SubWordFinder app = new SubWordFinder();
        ArrayList<SubWord> words = app.getSubWords();
        ArrayList<String> prefixes = new ArrayList<>();
        ArrayList<String> suffixes = new ArrayList<>();

        //System.out.println("DEBUG IN MAIN: " + words.size());
        System.out.println("* List of SubWords in the file *");
        for(SubWord temp : words){
            System.out.println(temp);
        }

            for(SubWord object : app.getSubWords()){
                prefixes.add(object.getSubWords().substring(0,object.getSubWords().indexOf(" ")));
            }
            for(SubWord object : app.getSubWords()){
                suffixes.add(object.getSubWords().substring(object.getSubWords().indexOf(" ")).substring(3));
            }

        //System.out.println(suffixes);
        System.out.println("pls be patient the following code takes a while to run");
        System.out.println("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMWWMMMMMMMMMMMMWMMMWWWWMMMMMMWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWMMMWMMMWWWMMWWWWWWWWNNNNXKKK00000KKXXNNWWWWWWWMMMMMMMMMMWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWMWWWWWWWWWWNNXXXXKK00Okxdllllllcc:;;;::cccclldxO0KXNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWMMWWNNXXXK0kxdollc:;,,;;;;;,,'.................',;:loxk0KNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXXK0Oxdollc::;;;,,'..'',,'...........................'';:coxOKXNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMWWWNXK0xoc::;,,'.......  ..'''.................................'',,;:coxkk0XNNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMWNX0kdl:;,,''................''............................''''..',,,,,,,,;;:ldOKNNNWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWX0xl;''......................'''''''''..............''''''',,,,,,'''''',,,,''',;:lxOKXNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMWX0xl;'..........................''..'''................',,;;;;;;;,,,,,,,'',,,,,;;;;;;;:ldOKXXNNWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMWNKkl;'...........................................'.....'',,;;::;;;;;;;;,,'',,,;;;;;;::::::;;:ok0KXNWWWWWMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWX0xc,.........................''''................''',,,;;;:::cc:::;;;;;;;;,,,;;::::::::::cccc::cldOKNWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOo:'...............'''.'.......''.''....'...''''.'',,,;;:::::ccc:::cc::;,;;:::;;;:::::::::::::ccccccldk0KNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMWXOo;...................''....''..''''''...',,,,''''',,;;::ccc:;::::;:::cc:::::cccc::::cccccc::c::::cllllcclx0XNNWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMWWXOo;.........''........'......'''''',;;,,,...';::;,,,;;::cccccc::;;;;;::::cccccccclllcc:::ccccccclc:::coddolccldOKXXNWWWWMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWXOd:'..........''....''''''''..',,,,;;:c:;::,'..';cc:;:cclc:::::ccc:;;:::::cccllclcccllllcccccllcccllcc::codxxdlccldO0XNWWWMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMWN0xc,'................',''',,,,'',;;;;::::;;:::;'...;::;;::::;;;;:ccccccccccccccccccccccccllooolooolccclllllloxxkkdlcloxk0XNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWKxl;'............'...',,''',;;;,'',:::::::;,,;;;:;'..',;;;,,,,,;;:cccclllllllllllllccloolllloooddooddollllooolloxkOOkdllodxOKXNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWXOd:,'.......''.......',,''',;;;,,,,;;;::::;,,,,;:c:'....,;;;;,,,,;cllccllooooolllloollldkxdooloodxxxxxxdooodxxdoodxk0K0kooddxOKXNNNWWMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMWWWWNKkl:'........''.......',,'''',;,,,,,;;,;::::;'''',:c:'....';:::::;;:cllllllodxxdolloodxoodOOkxdooddkOkxxkkkxdxkOOxooxkOKXX0xddxkk0KNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWNOdc:'.........''.......',,'''',;,,,,,;;,,;::;,'',,;:::,....';:ccc::::lodddolldkOkdooodkOkdxO00OkxxxkkOOOkkO0OxdkO0kdddkO0XNNKOddxkOKXNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWXOo:;'..........'.''.....''''''',,,,,,,;;,,;;;,,,,,,;:::;'...'';cllc:::cdkOkxolok00kxddkO00OO00K0OkkOO0000OkOO0Oxdk00OxdxOKXXNNXOdox0KKNNNNNNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWXkoc,...........''''.....'''''.',,,,,,,;;;,,;;;,,;;;;::::;''''..,cooolc:cdkOOOkoox0K0OkkO0KK00000000OO000000kkkOOkxxk0K0xxk0KKXNNX0dok0KXXNNNNWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMWXkoc,............'''......''''''',,,,,,;;;;,;:;;;;:::::::c:;,,,''':ldxdollokO000kdok0K0OO0KK000K000K0OkO00000Okxk00kxx0KKOxdk0KXXXNX0xoxOKXNNNNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMWXkol;...........'''''.....''''''',,,,;,;;;;,;:c:;;::::::ccll:::;,,',cxkkxdodkO0000xdx0K000KK00000000K0OOOO000KKOxxk00kxxOK0kddk0KK0KKKOdoxOKXNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkdl;'..........''''''.....'''''',,,,,;;;:;;;;:c:;:cccccclloolcc;,,'.;dO0OxddkO0000OxkO0000000K0OO0KKKK0OOkO000KKOxdk0Oxdk0K0kddk00OOOOOkdox0XXNXXXXNNWMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdl:'......'...'',''''....','',,,,,,,,,;;::;;:clc:clllcclooddol:;',,,:oO0OkxxkO00000OkkO000000KKOkOKKKK0OkkO0K00K0kdxkkkddk00kddxkOOOkxkkxdok0KXXXXXXNNWWMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkol:'......''...',,,,''....',,,,,,,,,;;;;:c:::cllllloolccodxxxxo:;:lodxxO0OOkxkO0K000OxkO00000000kkO0000OOkkO0K0OO0kxddxxxodkOOxdddkOkxxodkxodx0KKKKXNNXNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0dl:,...'...''...',,,,''...',;,,;,,,,,,;;;:cc::lllloddollldkkkxkdllxkkOOkxkOOkxkO000OOOxxkO0000000kxOOOOOkkkkOOOOkkkkkdodddooxkkxdooxkdddoodxxddkO0K00KXXXNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMWKxoc,...'''''''..'',,,,'...'',;;;;;;,,,;;;;:cc:clolodxdolllxkkkOOkodkkkOOkdx0OkxkO00OkkkxdxOOOOOO00kxkkkkkkkOkxxxxddxkkdooodolldxxolodddololldkxddk0KOxk0XXXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWKxol:'..',''''''.''',;,,'...',,;;;::;;;;;;;:clc:cooloxkxdlloxOOO00kddkkkkOkxxkkkxxkkOkxxxxddkOOkkkOOkxddxxxxkkxxdddooodxxdoodolclodolllodolllloxxdodO0Oxxk0XXKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOolc,..',,'''''..'',;;;;'..',,;;:::c:;;::::clolclddodkOkxoldO000K0OddxkkkkkkxxxkxxxxkxddddooxkkxxxkkkdooddddxxxdddooooodxdlllollcloolllloolcccclxxodxkOOdokKXXXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKxlc;'.';:;,,,,,..',;;::;,..,,;;:::cc:;::cclooolcodxddOOOkdoxO00KKK0xdxkOOkkkxdxxxddxkxdooooodxxdddddxdlloooodddddooolloodo::cllllccllllloolccc:codddddkkdodk0XXXXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNOdoc,'.,:cc::::;'',;:c:::,.',;;::::cc::clooodddlloxxdxO00kdok0KKKKK0xoxkO0Okkxdxxxddxxxolcloodddooooooocclllloooooolllllldo::cclccccclllllllccc::coddodxxdoodkKNNXXXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWKxol:,.';clclllc;'';:ccc:;,'',;;::::clccodxxxxxxoloxkxk0K0Odok0KKKKK0xodk0KOkkxxddddddxdoc:looooolllllllccccccllolllllllclolc::ccc::ccccccccccccc:;lxdoodddolldOKNNXXNWMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0dll:'.,;ccllllc;'';:cc::;,'';:::::clllcokOOOOkkoloxkxkKK0OxdkKKKKKK0xook0K0kkkxddddddddl::clllllccccllcccccccllllllcclccllllc:ccc::ccccccccccccc;,:odoodddolloxOKKXNXNWMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkdll;'.,:clcc:::,',;:::::;,,,;:ccccclllcoO0OOOOkdooxkxk0K0Oxdk00000KOdlokKXKOkkxdooddoddlccccllclcccclcccllccllolcccccllccclllcccc::ccccccccccccc:;;loddoddlclodkO0KXXXNWMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOdooc;'',cllc:;;;,,;::::::;,,,;:cccccloccoO0OO00Odooxxxk000OxdkO0OOO0OdlokKXK0kkxdooooooollllccccccccccccllllcllllcccccllccclolcccc::cccccccccccccc:;:ldolodoccllok0K0XNXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXxlloc;,';cllc:;;,,,;::::::;;,;;:ccccclol:okOOO00Oxodxxxk00OOxdxOOOkkOkdlokKXX0kkxdooooooolodlcc:ccccccclllllllllllcccclllcccloolccc:::ccccccccccccc:::odlloolccllld00OKNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXxcllc:,';cccc:;;,,;;;::::::;;;::ccccllol:lxOO0O0Okddxkxk00OOxdxkkkkkkkdlokKXXKOkxdoooooolloxdlcccccccccllllllllllccccllcccllcloolcc:::cllccccccccc:::clolloolccllldO0OOKNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKdlooc:,';::::;;;;;:::::::::;;;::cccclldo:cdO00000OxdxkdxO00kxddxxxxxxxoclkKXXKOkkdoooooolcokxocccccccccclllllllcclllllccllllccodolcccccllccc::ccccc:::cllllllccclloxO0kOXWNXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNOdoooc:,,;;;;;;;;;;:::::::::;;;:ccccllodoccdkOOO000kdxkddO00kxdddddddddoclxKNNX0Okxooollllcokxlcccllcccccllllllllclllllllllllcloolcllolccccccccccccc:::ccllllcc:ccllok0kx0NNXXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKxoolll:;,;;;;;;;;;:::ccc:::::;;:ccccllodolloxkkkOOOkdxkooxOOkdoooodoooooclkKNNXKOkxdllllllcokxocclllllcllllllllllllllllllllllllodlccloollcccccccccc:::::cllllcc:cclllxOxdOXNNXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0oloolc:;;;;;;::;;;;:::ccc::::;;:ccccllodollodxxkkkOkxxxoldxxxdooooooooooclkXNNXK0kkdllllllldkkdllllllllllllooolllllloooooooooooxxoccldolcllccccccc::;::::cllllccccclldOkdx0NWNXNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0dooolc:;;;;;;::;;;;::ccccc:::::::ccllloddoooddxxxxkkxxdlloddddooooooooolloOXNNNX0kkdllllccok0kdllooooooolooooollloooooooooddoodxkdlldxdllclllllccc::;;:::ccllccccccclokOxoONWNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMWN0xooolc:;;;:;:::;;;;:ccccc::::::::ccllllodoooodxxxxxkkxdllooooooloolloollld0XNNNX0kxdlcllclx00kdooddooddooodddoooodddddddddddodxkxdlokOdoolllllllcccc;;::::cccc:cccccclxOxlxXWWWXXWMMWWMMMMMMMMMMMWMMMMMMMMMWMMMMMMMWWWWWWWWWMMMMMMMMMMMWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMWNKxooolc:;;;:::::;;;;:ccccc::::::;:ccclcloooooooxxxxxkxxdlloooooolllllloloox0XXNNX0kxdoodolok00kdooddddddddddddoldxxxxxxxxdddddxkkdooxOOdooooloolllllc:::;;:::c:::ccccccoOxlo0NWWNNWWMMMMMMMMMMMMMWWMMMMMMMMWWMMMWWWMMMMMMMMMWMMMMMMWWWWMMMMWWWWWWMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNKkooolc:;;;;:::::;;;:ccccc::::::;;ccccccoooodoodxxxxxxxdolllooolllclllllodx0XXXXK0Okxddxddx0K0kxdddxxxxxxxdxxdooxkkkkkxxxxxxdxk0koldOKOdooooooollloolcc:;;:::::;::::cc:cxkodOXWWWNXWMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWMMMMMMMMMWWWMWWWWWWNNNNNWWWMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNWXOdoollc:;;;;::::;;;:cccccc:::::;;:ccccclooodoodddddxxddolcllollllcllccloddOXXNXXK0kxddddxOKK0kxxxxxkxxkkkxxxxddkOkkkkkkkxddxk00kolxK0kxddoooollodooooc:;;:cc:;;::::cc::dOxxkKNWMNKXWWMMMMMMMMMMMMMMMMWMWWWNNXXXXXXNWWWMMMWWMWWWWNXKKKKKKKKKKXXNNWWWMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWNOdoollc:;;;;::::;;;:cccccc:::::;;:::::clloodooodddddxdddlcclllllllllccoxxx0NNNNXK0OxdxdxOKK0OkxkkxkkkkkOkkkkkkkkOkkxkOOkdddkKKOxdx0KOxxxdddddodkkxdddl;,;:cc:;;::::cc::oOOxd0NWMNXXNWMMMMMMMMMMMWWWWWWWNXKKKKXXXXKKKXXNNWWWWWNXXKKXXNNNNNXXXKKKKXNWMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWN0dooolc:;;;;:::;;;;;ccccc::::::;;::::::lloooooloddddddddlcclllccllllcldkkkKNNNNXK0kxxxkOKXK0kkkkkkkkkkkOOkkOOOOOkkkkkOkxddkKNKkdkKX0OxxxxxxxdxO0Okxxdo;,;:cc:;;::::cl:;lOKxoONWWWWXXNWMMWWWWMMMWWWWWWNXKKKKXNWWWWWNNNXXXXNNNNXNNWWWWWMMWWWWWNNXKKKNWMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNWMWKdloolc;;;::;;;;;;;;ccccc:::::;,,:ccc::cllloollodddddooolcclllcccllcldO0kkKNNNXXXKOkkkOKXXKOkkOOOOOOOOOOOOOO0OOOOOOOkOkddOKXX0OOKXKOkxxxxddddOKK0Okxdl;,;:cc:;;::::cc:,ckKkdONWMMWXXWMMMMMWWWMMMMMWNXK0KXNWWMMWWMMMMMWWWNXXNNWWMMMMMMMMMMMMWWWWNKKXNWMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNWWMWKxloolc;;;;;;;;;;;;;:cccc:::::;,,:::cc:ccccldl:loooooooolcclllllllcclx00OOKNNNNXXKOkxxOKK00OkOO0OOOOO0000000OOOOOOOOOOkkOKNX00KK0OOkxdolcc:;:cldO0Okxl;;:ccc;,;::::cc:,cxK0kOXWMMMNNNWMMMMMMWWMMMWNXK0KNWWWWMMMMMMMMMMMMWWWWMMMMMMMMMMMMMMMMWWWWNXKXNWWWMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNWMMWXxooolc:;;;;;;;;;;;;:cccc:::::;,,;::cc:cccclxo;:looooooolcclllclllllok00OOKNNXK00OkxkOKK0OOOOO0000000000000OOO00OOOOOOOKXXKKXNNK00Od;'.....'...,cdxxdc,;ccc:,,;:::::cc:cxKK0OKWWMMMNXXWMMMMMMMMWWWXK0KXWMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXKXNWWWWMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWMMWXkoollc:;,;;;;;;;;,;:cccc::::;;;,,;:c::::::cxo,,:lloolloolccllclllclx0X000KK0OkxxxdodxkkkkkO00000000KKKK0000000KKKK00KXNNNNNNNNX0kl,. .,odolc,'';:cooc;:ccc:,,::::::cldoxKX0O0NWMMMNKXWMMMMMMMMWWNXKKXNWWMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMWXKKNWWWWWMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNWMMMNkoollc:,,,;;;;;;;,;::cccc::;;;;,,;::::c::;cxo,';cllllloolccclllllox0XKkdollc:,'';c:;;:cclokO00000KXXXXXXXXNNNNXXXXXNWWWWWWWWNKkl;.....'ckOOko:,;cll:;;:cc:,,,:c:::::oxdxXNKk0NWMMMWXXWMMMMMMMWWWNX0KNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMWXKXNWWWWMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMWMMWNNWMMMMNOdllcc:,,,;;;;;;;,;:::ccc::;;;;,,;::::cc:;cdo;.':llllllolccclccclxOOdl,........,ccclool:;:lxO0XNNNNNNNWWWWWWNNNNNWWWWWWWNNWNXOo;.. .',.,kNXKOxc;:ll;,:ccc;',;cc:::;;oxoxXWKk0NWWMMWNXNWMMMMMMWWWWX0KNWWMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWMMMMMMMWNXXNWWWWMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMWWMMWNNWMMMMNOdlccc:,,;;;;,,,,,,;:::::::;;;;;;;:::::c:;:do:'';:clllloolcclcclll:,..  ..  ..,::,;oOOOkdlclkXNWWNNWWWWWWWWWWWWWWWWWWWWWWWWNXkl,. .;xx;'dNWWN0dc:cc,,clc:'',:cc:::;;lxdxXWXk0WWWMMMWXXNMMMMMMWWWWXKKXNWMMMWWMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMWWWNXXNWMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNWMMMMMN0xlccc:;;;;;;,,,;;,,::::::;,,;;,,;:::::::;:loc;,,:cccccloolcc::;;'....'.......';cc;'oKNNX0OkOKNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXx:'...cxd,.l0NWWNOdlc:;;cl:,'';::::::;;lOxkNWXk0NWMMMMWXXNMMMMMMMWWWWNXKXWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNXKNWMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWMMMMMWXkoccc:;;,,;;,,,;,,,;:::::;;,;;,,,;,;;;;:;:looc;,;:cc::codoc;::;,,,'.'''.......lOkc.,dXWWWNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWKl'..',,,'.'cONMWNKkdl::cl:'.';:::;;::;'cO0KNWXk0NWMMMMWNXNWMMMMMMWWWMWNXKXNWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMWWWNXXXWWMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWMMMMMMWNOoc:::;;,,,;,,,,,,,;;:::::;;;;,,,,;cc:;:;;colc;,,;:::;:lol:;;;:cdl'.........',:l:,..:0WWWWWNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW0c....,clc::lONMWNKOko::c:'..,:::;::;:;.;xKNWWXkONMMMMMMWNNNWMMMMMWWWWMWNXKXXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXXNWWMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWMMMMMMWNOo::::;,,,,,,,;,,'',;:;;;;;;;;,',cx00Okdc:cooc;,,,;::;;:lolc::lk0o.   ........';cc;';ONWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKo,...;oxxooxKNWWNK00xc:;'..';:::;;;;;,.;xXWMWXkONMMMMMMMWXNWMMMMMMMMMWWWWNXKKXNWMMMMMMMMMMMMMMMMMMMMMMMWWWWWWXXXNWWMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNWMMMMWMWXOl:::;;,,,,,,;;;,'',;;;;;;;;;;,'ckKXK0KKKOdooc::;;:;;;;;codolcoOXOc....,:;....,ldxl:cONWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXxlcloxOK0kk0NWWNNX0xl;'....';:::;,,;;'.:ONWMWXOONMMMMMMMWXXWMMMMMMMWMMMMMWWNXKKXNWMMMWWMMMMMMMMMMMMMMMMMWWNNXXXWWMWMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWMMMMMMMWKxl:::;;,,,,,,;;,,'.';;;;:;,,;;,;dKX0kkO0KXX0xc::clc;,;;::ldkxookKXk,..;:ll:;;:ldkkxod0NWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNKKKXXNNWNKKXWWWWN0do:.....',;::;,'';,..lKWMMWN00NMMMMMMMWXXWMMMMMMMMMMMMMMMMWNXKKXNWMWWWWMMMMMMMMMMMMMMMWNKKXNWWWWMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWMMMMMMMNOdoc::;;,,,,,,,,,'..',;;;:;,,,,:lOXK00KKK000KKOoc:col;;;;:cdkOOkxkKKd;;cldxkkk0KXXK0O0NWMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWNNNXNWWWWNKOOOl.....,;::,''',,,';xNMMWNXKXWWMMMMMMWXXWMMMMMMMMMMMMMMMMMMWNXKKXNWWWWMMMMMMMMMWWWWWNXXXNWMMMWWMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWMMMMMMMNOdol:;;;,,,,,,,,,'..',;;;;:;,,,:xKX00KXXK0OO0XNKkllxd:;:;;cldkKXKO0XX0kxkO0XNNNNNNNXXNWWWWMWWWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNWWWWNNXKKXXKo....';:;,''',,,''cOWMMWK0XNWWMMMMMMWXXWMMMMMMMMMMMMMMMMMMMWWNXKKXNWWMMMMMMMMWWWWNXKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMNOddl:;;;,,,,,,,,,,'..';;;;:;,,':kXX0OKXKKK0000XNXOxkxl:::::cox0XNXKKNWNXK0KXNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNWWWNNXXXXXXX0l....,;,''.',;:;''l0WMMW0OXWMMMMMMMMWXXWMMMMMMMMMMMMMMMMMMWWWWNNNXXXXXNWWWMWWWNNNXXNWMMMWWMMMWWMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMWXOkko:,,;,,,,,,,;,,'..',;;;:;,'':kXX0O000KK0Oxx0XNX0kxdc;::;:lxOKNNNNXXNNNNNNNXXXXXXNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNXXXXXXKKXKl..';,'..'',,,:l;,l0NMWN0OXWMWWMMMMMWXXWMMMMMMMMMMMMMMMMMMMWWWWWWWWNXKKXXXNNXXXXXNWWMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMNK0OOd:'',,,,,,,,;;,''..,;;;;,'',;d0XKOkO00O00OO0XNNX0Okc;;;;;lxxOXNNNWNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNXXXXKKKXKo'',,'..'',,,,:dc,oKWMN00XWMMWWMMMMMWXXWMMMMMMMMMMMMMMMMMMWWMMMMMMWWWNNXXKKKXXNNWWWWWWMMMWMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMWNWMMMMMMMWX00K0d:'',,,,,,,,;;,''..',;;;,,''';dKN0k00kO0K0OxkKXNXKOo:;:;:oxxk0XNNNNNNNNXNNNNXNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNXXXXKKKKKKx:,''.'''',,,,ckl,oXWWKk0WMMMMWWWMMMWXXWMMMMMMWWWWWWWWWWWWWMMMMMMMMWWWWWWWWWWWMMWWWWMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMWNWMMMMMMMWKOKNKd:..',,,,,,,;;,'..'',,,,,''''.;o0XXKOxxOK0Oxxk0XXXKko::::oxkxkKNNNNNNNNXXXXXXXXNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNXXXXKKKK0x:'''''''',,';dOo;dXN0OKNWMMMMWWWMMMWXXWWWMMWWNXKKXXXXXXXNWWWWWMMMMMWWWWWMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMWWWWMMMMMMMW0kKWXx:...'',,,,;;;,''.'',,,,,',,'..'ckKXKkxxO000kxOXXXXKxc:::lxOkxkKXNNNXXXXXXXXXXXXXXXXNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNXXKK00d:'.'''''',''ck0l;xXKxxXWWWMMMWWWMMMWXXWWWWWNKKXXNNWWWWNNNNNWWMMWWWWWWWMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMWNNWMMMMMMWMWOdKWXk:....',,,,;;;,,'.''',,,,',,,....;lk00OOkkkkdox0XNXKkl:::lxOOkxkKNXXXXXXXXKKXXXXXXXXNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNXXKKKx:'..''''',,,l0Xo;xOdONWWWWMMMMMMMWMWXXWWWWXKKXNWWWWWWWMWWNNNWWWWNNNNNNNWWMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMWNNMMMMMMMWMWOdKWNk:.....,,,,,;;;,'..'',,,,',,''..',,;cokO000kdoodOKXX0dc::ldO0OkxOKXXXXXXXXXXXXXXXXXXNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNXXNXk:'''''''',,;o0Xd,:dkKWWMMMMMMMMMMMMWXXWWWWXKXWWWWWWWMMWWWWWNNNNNNNNXXXXXXNWMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMWNOxKWNk:.....',,,,;;;,''.'',,,'',''...',;,,,:lxk000Okkk0KXKkl::coOKK0kxkKXXXXXXXXXXXXXXNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNXx;'''...'''',xXXo':kXWWWWMWWWMMMMMMMWXXWMMWXKNWWWMMMMMMWWWWWWWWWWWWWWWWNKKKNWMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMWX0OXWNkc'....'',,;;;;,'..'',,''','....',;;;,;;,,cxOO00OO00K0o::clkXNXKkxx0XNXXXNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNKo'.'.''''''',x0kolkXWWWWWWWWWMMMMMMMWXXWMMWXXWMMMMMMMMMMMWWWWMMMWWWMMMMWNXKXNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMWNWMMMMMMMMWK00NMNkc'....',,,,,;;,'..'',,''''''...',;;;;;;,',loccoxdllxOxl::ckXNNXKOxx0XNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNXkc'.''',,'',,':llloONWMMMMMMMMMMMMMMMWXXWWWWXKNWWMMMMMMMMMMMMMWWMMMMMWMMMWNKKXNWMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMWWMMMMMWNWMMMMMMMMN0OKNMNOc'....',;,,,,;,'..'',,''''''...',;;;;::;',oo;,lxxdddxxdc:lxKNNNXXXOkOKNWWNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNN0l,'.'',,,'',,':dOxoONMMMMMMMMMMMMMMMMWXXWWWWNKXNWWWWMMMMMMMWMMMMMMMMWWWMMMNXXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMWWMMMMWWWWMMMMMMWMXxkXWMNOc'.....,;,,,,;,'...',,''.'''...',;;;;;;;,,lo:;lxOOkxooo:;cd0NNNNNWNKOO0XNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMWWWMMWWWWWWWWNNN0d:''.',,,,'',,,dXNOx0NMMMMMMMMMMMMMMMMWXXNWWMWNXXWWWWMMMMMMMWWWMMMMMMMMMMWWNXNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMWWWWMMMMMMWWWKdxNMMNOl,.....',,,,,;,'...',,''..''...',;;;;;;;,,clc:lxkkkkxoc:::d0XNNNNNNNNKOO0KXNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNWWMWWWWWWWWWWNWWWXko:;;,'',,''',,',xNW0x0NMMMMMMMMMMMMMMMWNNNWWMMMWNXXNWMMMMMMMMMMMMMWWWWMMMWWXKXNMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMWWWWMMMMMMMWWKoxNMWN0l,.....',,,,;;;'...',,''..''...',,;;::;;,,:ll:cdkxkkxoccccoxOKXNNNNNNNNXK0O0KXNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNWWWWWWWWWWWNWWNN0d:;;;;,,,,,,,,,,''dNWKkOXWMMMMMMMMMMMMMWNNNWMMMMMMWNKXWWMMWMMMMMMMMWMMMMMWWNXXNNWMWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMWNNWMMWMMMMMWKdkNMWW0o,.....',,,,;;;'...',,'...'....',,;;::;;,,:ll::okkkkxdlcc::ldxO0KXNNNNWWNNNXXXXNNWWWWWWWWWWWWWWWWWWNNXXXXNNWWWWWWWWWWWWWWWWWWNWWWNNWNKxl:,;;;,,,;,,,,,,,''dXWXOkKWMMMMMMMMMMMMMWNXNWMMMMMMWWNXNWWWWWMMMMMWWWWWWWWNNNNWWWMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMWNWWMMMMMMMWNKxOWMMW0o,.....',,,,;;;'...'','........',,;;:;;:,,;coc:oxxxxxdol:;;codddxk0KXNNNNWWWWWWNWWWWWWWWWWWWWWWWWWWWNNNNNWWWWWWWMWWWWWWWWWWWWWWWNNNKOo:;;;;;;;,;;,,,,,,;,,dXWN0xOWMMMMMMMMMMMMMWXKXWMWWMMWWWWNXXNWWMWWWWMMWWNXXNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMWWNMMMMMMMMWX0kKWMMW0o,.....',,,,;;,'....','........',,;;;;;:;,,:oc:oxxdddxdc::;codddxxdxkO0KXXNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNKko:;;;;;;;:;;;;;,,,,,;,,dNWNKdkNMMMMMMMMMMWMWNXXNMMWWMMMMMMWNNXNNWWWWWNNNNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMWKOOXWMMW0l'.....',,,,;;,.....','........',,;;;;;;;,':dl:oxxddddollc:codddxxdddxxkkO0KXNNWWNWWWWWWWWWWWWNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWX0dl:;;;;;;,;::;;;,,,,,,,,,,dNWWKoxNMMMMMMMMMMMMWXXWMMMMMMMWWMWWWWNXXXXXNNNNWWMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMW0x0XWMMW0l'.....',,,,;;'.....'''........',,,,;,;;;,'cdocodoolc::colcloxxxddxxxxxxxxxxkkO0KXNNWWWWNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWNKOdl::;;;;;;;;:c:;;;;,,,,,',,,dKWMKodXMMMMMMMWMMMMNXXWMMMMMMMMMMWWWWWWWNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMWNWMMMMMMMWOdKNWMMW0l'.....',,,,;,'.....'''........',,,,,,,;,,,colccc;,'..':loccoxkkkkxxxxxxxkkkkxxxxkO0KXXNNWWWWWWWWWWWWWWWWWWWWWWMMWWWWWWWNXKOo::::::;::;;;;:c:;;;,,,,,''',,o0NMXddXWMMMMMMWMMWNNNWWMMMMMMMMMMWWWWWMMMWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMWNWMWWMMMMNxoKMMMMW0l'.....''',,;,.......''.........',,,,,,,,,;cllc:;'....,:loc:ldxkkOOkkkkxxxxxxxxxxxxxxxkOO0KXNNWWWWWWWWWWWWWWWWWWWWWWNNWNKxl::;;::::;;;;;,;cl:;;;,,,,,,'',;lONMNkkKNMMMMMMMMWWXXWMMMMMMMMMMWWMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMWNWMWWMMMMNxoKMMMMW0c......'''',;,.......'..........','',,,,'';::llc:;,,,,;codlcldxkkOOkkkOkkxxxxxxxkkxxxxxddoooxk0KXNNWWWWWWWWWWWWWWWNNNXKxlcc:::;;;;;;;;,,,;lo:;,;,,,,,,'',;:xXMN0OONMMMMMMMMWNXNWWMMMMWMMMMWMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMWNWMMMMMMMNkdKWMMMNOc......'''',,'.......'..........''''''''.';:;loc::cllcccodocldkkkkOOOOOOOOkkxxxkkxxxxxxxxxdoollloxO00KXXXXXNNNNNWWNKOxl:;:cc:;;;;;;;;;,,;;lo:,,,,,,,,''',;;oXWWKkxKMMMMWMMWNKXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMWNWMMMMMMWNkxKWMMMNk:......''',,'.......''..........'''''''..'::;coc::cdk0OkxooccdkkkkkOkkkOOOOOkkxxxxxxxddxxxxdddolldkOkkkkkOOOOkkOOkxdlccc::::::;;:;;;;;;;,;ldc,,,,,,,''''','c0WWNkd0WMMWWMWNXXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMWNWMMMMMMWKOOXWMMMNx;.......'',,'......'''..........'',''.....:c;:llc:cx0XXXK0kocoxkkkkkkkOOOOOOOOkxxxxxddddddddodol:cx0KOkkkkkkkdoollllolllc:::c::;;;;,;;;;,,ldl;,,,,,'',,'''.;OWMWklOWWWMMWNXXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMWNWMMMMMMN0O0NWMMMNd,.......'',,.......''...........''''.....'::,,:loodkKKXXXNXkcokOOkkkkkkkkkkOOOOOOkkxxxxxddddddoc,';d00Okkkkxxxddoollollc:::::cc:;,;;;;;;,,lxdc;,,,'''''.''.;kNWWOokNWWWWNXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMWNWMMMMMMXOOKNMMMMXo'.......',,'......'''............''......,c:'';lddxO0XXKXNNOodOXNXK0OkkkkOOOOkOOOOOkxxxdxxdddoc;,,;:dKKkxxxxddoollllllc::::::clc;,;;;,;,,,cdOd;,'''..''....;dKWW0xOXWWWNXNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMWNWMMMMMMXkOXWMMMMXl........','.......'''............'......';c;'.;oxxkO0XXXXNNOookXWWNNXK0OOOOOOOOOOOOOkkxxxxdddoc,,,;,lKWKkxxxxddoolccccccc:::::loc;,,,,;;,,:d0x;''''........,:kWWXOk0NWNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMWNWMMMMMMKxkNWMMMMXc........,,'.......'''.........''........';,..':oxxkOKXXXXNX0dlxXWWWWWNNXXK00OOOOOOOOOOkxdxxdool:;;;;oKWNKkdddddoollllcccc:::::cdo:'',,;,,,;o0k:'...........',dNWN0xkXWNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMWNNWMMMMMM0okNWWMMMXc........',.......'''..........''.......',,..';coxxxOKXXXNXXKxloKWWWNNWWWWWNNNXXKK00OO00Okddddoc:::;;oKNNNKkxdooooollcc:::::::;:dd;',,,,,,,,cO0o,.............lKNNKdxXWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMWNNWMMMMMM0okWMWMMWKc.......'''......',''.........''.......';;'.',:loxkkOKXXNNXXXOll0NWWWWWWWWWWWWWWWWWNXK0000kxxdoc;:c::o00O0XXKkl;:c:cooc:clc:;;;:xx:'',''',,'c0Xk:''..........'ckNWXddXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMNNWMMMMMW0okWMWMMW0:......','.......,;,'........''........,:;'.',:loxxkOKXNNNNXN0olkXNWWWWWWWWWWWWWWWWWWNNXKOOkkdlc:clllx0xccxXNXkc;ccd0KOxOOdddo::xOl,','''''':kN0c''..........',lONXxdKWWMWMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMNNWMMMMMN0d0WMWMMNk:......','.....'';:;'........''.......';:;'.';:cldxkOKXNWNNNNKdcdKWWWWWWWWWWWWWWNNNNNNNNX0OOOkolllloox0kc;ck0XXOloOOk0XXXK0XXOo:lxdc'.'''''':xXKd,.............;xXN0kOXWMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMNNWMMMMWN0kKWWWMMXx;......''......';cc,........','.......',''...,::coxxOKXNWWNNWXxcl0WWWWWWWWWWWWNNNWWWWKxkKXKOOOxlcclddk0Ol::odOXKo:xKKK00KNWNX0xl;''...'''..';o0X0l'............;dKWXOd0WMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMWNWWMMMWXOOXWWWMMXd;......'.......'co:'.......'''............  .';:cldxO0XNWNNNWNxccOWMWWWWWWWWWWWNWWWNKxccd0NK0Oko::lldO0Ooc:::o0KKKXNXKKNNNXKKKKK0d:'.  ......,:dkd;'............;kNWOlkWMMWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMWNNMMMWKOOXWMMMWKo;.. ..''.......,oo,........','............  ..,:ccoxO0XWNNNNWXxc:kWMMMWMWWWWWWNNWWWXx:;:lxKXK00kddoodO0koccooxKXNNNXNNWWN0O0XNNNXNXOo:'..   ....,:c;.............lXW0okNWMWNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMWNNWMMWKO0XWMMMW0c'.....'.......'cxl......',,'................. .,cccok0NWNNXXNXxccxXWWMWWWWWWNNNNNWKd:;;;:lxOKXK0Okxxk0XOox0KXXXXXNNWWWXOl;:d0NWNNXXXX0Okdc,......,clc:;,.........:kXXkkKNMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMWNNWMMN0k0NMMMMWO,.....''.......cxd;....',,;,'.................  .,:coxOXWWNNNNXxccd0NWWWWWWWWNNNNN0d:,;;,:ldxOKXXK0kx0XKOOKXXXXXNWWNN0d:'...'cxKXKKXNXKXNNX0x:'...';clcclodoc;'...'cOX0kOXWWMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMWNNWMMNOkKWMMMMWx'.....'........;l;......................  ........,:ldkKNWNNNWXxlcokXNNNNWWNNNXK0xc'';;;;;codxOKNX0kkKXKKXKKXXNWWNX0d;.......'ckKXNNXXNNXXXXXKkl,..,ccc:ldxxxxdoc,.'dNXxdKWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMWWWWMNkxKWMMMWNd.....''...................  .......................';cdOXWWWMMNkl:lkXNNNNNX00K0kxolc;,'',;codddkKNNKO0XXKKKXNNWWNK0kl,......;d0NWWXO0XWWWWNXXNXKxc'';lllldkkxxkO0Oo;lOXxl0WWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMWNNWMXxdKWWMMWKo'....'.......      ........  ........................,cd0NWWMMNkl:lkXWNNNX0kO000OOOkxdlc:::loddxkKNX0KXXXNNNNNNX0kOOxc...;okKNNNNKx::okKXNWWWWNNNKxclddodxOOOOO0XXKkloK0xONWWWNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMWNNWMXdoXWWMMNOl'........   .....   .  ...  ..........................':dKNWWWXxccoOXWNNNX0kO00OOO0OO0Okxdooodxxdk0KXXNNNNNNXK0kkkOOOx:;d0NWWWK0XXX0xdoox0KXXNNWWWNKkdodxO0KKKXXXXNXxd0KOx0WMWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMWNNNWXdoXWWWWXx:........  .,:c;'.  . ..  .................. ............,o0NWWXx::dONWWNNXOkOOOOOOOOO000OOOkkxddxOXNNNNWWNNKOkxxkOOOOO0KXNNWNOlcoOXNNNXKK0000KXNNXXNXKOkkKNNNXNNXNNNXOk0OoxNMMMWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMWWWNWXddXWWWWKo,..... ..';cloooc,.........................................ckXWXd:cd0NWWWNKOkOOOO0OOOOOOOOOOOkkxk0XWWWNNWWNKkdooxkkkOKXXXNNKkl,...'cx0XXXNNNNNNNNXXKKXNNXKXNNNNNNNNNNW0dOKddXWMMWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMWWNNXxxXWWWWKc.......;clolllllcc:;'...............................'''.....'lkOd:cdKNWWWNKkxkOOOOOOOOOkkxxxxxO0KXWWWWWWWNKkollldk0KXNNNNXkl;...',:ok0XNWWNKKKXNWWNNXXXNNNNNNNNNNNNNNWKkOKOkONMWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMWWX0xkNWWWW0:...';codddddddolllllc;'................. ...........''''.... .';::lkXWWWWNKxdkOOOO00OOOkkxddox0XNNWWWWWWNXKOxxkOKXNNNNNXKx:..';cx0KXXNNNKkl::cdOKNNWWWNNNNNWNXXNWNNNNWNX000kdKWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMWMWXOxONMWWNO;.':oodxxxxkkOOOkkkkxxol:,......................'''...''''.......':oOXWWMWNKxdk00OOO0OOkkkkdodOXNNNNWWWWNNNNNXXNNWWWNNX0Okxc;cdOKXNNNNKko:,.....;oOKXNWWWNNWWWNXNNWWWWNNNKOKkoOWMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMWMMNKO0NWWWXx;'cddoddxkOOOOO0000000Okxoc,'...................'''''''''''......;cccoONWWN0olxO0OOO00Okkxxxk0XNNNNNWWWWWWWWWNNNNWWXK0kxxOOO0XNNNXXKK0kl,........:xO0KXNWWWWWWWNKXWMWNNNXXKKOxkXWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMWWMWKOONMMWKdcldxddxkO000KKXXXXXKKKXXKOkdoc,...........'........''''''''''''',:c;...:d0XOc;dOOOOOOOOkkxdx0XNNWWWWWWWWWWWWWWWWWNNNK000KXNNNNNXKOkO000Oxc,......;x00OOKXNWWWWWNXXNWWWNNXXX0OOxkNWWWMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMWMMNKkkXWWNOddxxxxxOKXNNNNNWWWWWWWWWWWNNK0kdc'..''...''''..........'''''''''';cc,... .,cc,'okOOOOkkkkxdxOXNNNWWWWWWWWWWWWWWWWWWWNXNNNNNNNNXKko:;cdO000Oxl;''';o0K0OkOKNWWWWWWWXXNWWWNXXK000odXMMMMWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0OOKNWW0xxkkxxk0XNWWWWWWWWMMMWMMWWWWWNX0Oxc,......''''.........''''''''',:c;''''.......:xOOOkOOkxodOXNNNWWWWWWWWWWWWWWWWWWWWNXNNNNNNNXkc;'''',lk0000OkxxkOKKKK0kkKNNWWWWWWNXKXWWWWNXKKOddKWMWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMWX00KXXNWKkxkkkxk0XNWWWWWWWWMMMMMWWWWWWWWNX0Od:.......'''.......'''''''''',::;'.'''......'lkOOOOOkookKNNNWWWWWWWWWWWWWWWWWWWWNNNNNNNN0xl,',,''',,:ok000KKKKXKKKK0OOKNNWWWWWWWNKKNWMWNXK0OkxxKWMWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMX00XNNKK0OkkxkkOKNWWWWWWWWWMMMMMWWWMMMWWWWNKOxl'......'''''''.'''''''''.',;;'''''''''''..;lxOOOkddkKNNNNWWWWWWWWWWWWNWWWWWWNNNNNNXOo:,'',,,',,,,',:dO000KKKKKK00O0KNWWWWWWWWWNXKNMMWNXK0OxlkWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMWX00XWWX0kOOkkkk0XNWMMWWWWWWMMMMMWWWMMMWWWWWWNKOd:.......''''''''''''''.'',;,'',,,''''''''';lxkkdokXNNNNWWWWNWWWWWWWWNNWWWNNNNNNNKkc''',,',,,,,,,'',:lxOKKKKKKK0000KXNWWWWWWNNWNXXWWMWWXK0xlxXWWMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMWXO0XWMWX00OOOkk0XWWWWWWMMMMMMMMMMMWWWMMMMMMMMWN0xl,......'''''''''''''.'',,''''''''''.''''';collkKNWWWWWWWWWWWWWWWWWNNNNNNNNNXX0d:',,,'''','',,,,,,,;cdOKKK00000000KNWWWWWNWWNNNKKXWWWWNKkddOXWWMWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMWMMWXO0XWMWNK0OOOOO0NWMWWWMMMMMMMMMMMMMWWWWWMMMMMMWNKOd;......'''''..''''...''''''''''''.''''''',;:dKNWWWWWWWWWWWWWWWWWNNNNNNNNNNX0o;'',,,''''',,,,,,,,,,,;cxO00OO00000KXNNNNWNWWNNNX0kxk0KXK0kooKWWMWMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMWMMWXO0NWMMNX00OOO0KNMMWWWMMMMMMMMMMMMMMMWWWWWMMMMWWNX0xc'......''''''......'''''''''''''''''',,''o0NWWWWWWWWWWWWWNNNWWNNWWNNNXXXOo;',,,,,,''',,,,,,,,,,,,,;:ok000OOO00KXXXNWWNNWWWWWXOoccldk0OolOXWMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMWXO0NWMWNK0000O0KNWMWWWMMMMMMMMMMMMMMMMMWWWWWMMMWWWNXOd;.......'''......''''''''''''''','''',,lONWNNWWWWWWWWWWWNNNNNNNNNNNNNXOl,',,,,,,',,,,,,,,,,,,,,;;,,:dO00OOO00KXXXNNWNNWWWWWNXOdccccokOxdONWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMWKO0NWMNK00000OO0XWWWWWMMMMMMMMMMMMMMMMMMMWWWWWWWMWWWNKx:...............''....'''''''','''''.:OXNWWWWWWWWWWWWWWNNNNNNNNXNXXKkl;'''.',,''',,,,,,,,,,,,;;;,,;cdkOOOOOO0XXXXNNNNNWNNNXXKOdlc:lxK0dxXWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMWWWKOKNMWN0O0K000O0KXWWWWMMMMMMMMMMMMMMMMMMMMMWWWWWWWMMWNKx:'.........''''....'..''''''','','',dXNNNWWWWWWWWWWWWWNNNNNNNXXNKOx:,''''',,,,,,,,,,,,,,,,,,;;;;;;;:ldkOOOkOXXNXNNNNNNNNNNXKKOdc;lOXN0O0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMWMWXOKNMMXkkO0000000KXNWWWWWWMMMMMMMMMMMMMMMMMMMMMMWWWWWMN0xl'......''''''...'''''.''''''',,,;o0NNNNNWWNNNNNNNNNNNNNNNNNXXKxo:'''''','',,,,,,,,,,,,,,,,,;;;;;;;;:okkkkk0XNNNNNXXNNNNXK0KKkolxXWWNOxKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOKNMMXxx000000000KKXWWWWMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWN0xo,......'....'''''''''''''',lddod0NNNNNNNNNNNNNNNNNXXXXNNXXX0d:,,'''''',,,,,,,,,,,,,,,,,,,;;;;;;::,;oOOxxxk0KNNNNNNXXXK00O00O0KNWMMNKO0NWMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMX0KNWMKoo00000000000KXNWWMMMMWWWMMMMMMMMMMMMMMMMMWWWMWWWNKko;......''..''''''''''''';d00xdkXNNNNNWNNNNNNNNNNNXXXXXXKKOo;''''''','',,,,,,,,,,,,,,,,;;;;;;;;;;;;:oOKKOkxk0XNXXK0OkkO000KXWWWWWWWNX00XNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMX0KWWW0clOKKKKK000000KXNWWMMMMWWWWMMMMMMMMMMMMMMMMWWMMWWWXOko,......''..''''''''''''cONXOk0XNNNNNNNNNNNNNNXXXXXXXKOko:,,,,''''''''',,,,,,,,,,,,,,,;;;;;;;;;;;;;:lxO0000KKKK00000XNNNWWWWWWMMMWWWXKKXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMX0KNWW0clO00KKKKKKK000KKXNWWMMMWWWWMMMMMMMMMMMMMMMMMMMMWWNXOdl,...........'''.''''';dKNNXOO0XNNNNNNNNNNNNNXXXK0Odoc;,,,,''''''''''',,,,,,,,,,,,,,;;;;;;;;;;::;;:coxkkO0XNNNNNWWWWWWWWWWWWMWMWWWWWXKNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMX0KNWNOllxO00KK000KK00000KXNWMMWWWWMMMMMMMMMMMMMMMMMMMWWWWN0kxl,.........'''......,oKNWWNKOO0KKXXNNNXXXXXXKOkxdl:;'',,,,'',,''''''',,,,,,,,,,,,,;;;;;;;;;;;;::;;:lxkkkk0KNWNNWWWWWWNNNNWWWWWWWWWWNNNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0KNWXkl:ok00000KKKKKKK000KKNWMMWMMWWWWWMMMMMMMMMMMMMMWWMWWNKkdc......'..'''''''.':kNWWWWWXOkkO0KKKKKKK00Okollooool:,'',,,,,,,,''''',,,,,,,,,,,;;;;;;;;;;;;;;;;,:lxkkkkkOKXNWWWWWWWWWWWWNWWWWWWWWWNWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKKNNKxc;cx00000KKXKKKKK0000KXNWMMMWWNNWWMMMMMMMMMMMMMMMWWWWNKkl'........'''''''':kXWMWWWWWXKOkkOOO00OOOkxolodolllool:'',;;,,,,'''''',,,,,,,,,,;;;;;;;;;;::;;;;;;cdxkkOOO0KXNNWWWWWWWWNNNNNWWWWWWWWWWMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKKXN0dc;;cx0KKK0KXXXKKKK00000KNWWWWWWNNNWMMMMMMMMMMMMMMWWWNNNKd;'.........''''':xXWWWWWMMMWNXKOkOOOOOOOkdooooollc::lol:,,,,,,,'''''',,,,,,,,,,;;;;;;;;;;;:;;;;::lodxkOO00KKKKXNWWWWWWWWWWWWWWWWWWWWWMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKXNOoc:;,ckKKKKKXXXKKKKKKK000KXNNWWWWWWWWWMMMMMMMMMMMMMWWXKNXOl,........''...:xKNWWMMMMWWWWWWX00OkkOOOkdooolllllc:;lkx:,,,,,,'''''',,,,,,,,,,;;;;;;;;;;;;;;;;:oxxxxxxkO0KXKKKKXNWWWWWNWWWWWNNNNWWWMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKKXkl::,',lkKKKKKXXXKKKKKKKK000KXNWWMWWWNNNWWWMMMMMMMMMMWXKKXXk;.........':cokKNWWWMMMWWWWMMWWNXK0Okkkdoloooolccc:;ckkl:;,,,,''''',,,,,,,,,,,;;;;;;,;:::;;::;:dOOkxxxxkO0KXXXKKXXNNWWWWWWWNNNNNWWWMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKKXxc::,'.,lO00KKXXXXXXXKKKKKKKKKXXNWWWWWNNNNNNNWWWMMMMMMWXKXNOc.......,cx0KXNNWWWWMMMMMMMMMMWWWWWNXXK0OOkkxxxxdddxO0d:,,,,,,,'''',,,,,,,,,,,;;;;;;;;;::;;:;:oxkkkkkkxxxxxkkOO000KKXNNNXXNNWWWWWWWMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNK0Xx:::,'..,o0KKKKXXXNNXXKXXXKKKKKKXNWWWWWWNNXXXNNNNWWWWMMNKXN0o;.....;dXWNXKNWMMMMMMMMMMMMMMMWWWWNXKKKKXXXXNXXXXXX0d:,'',,,,,,''',,,,,,,,,,,;;;;;;;;;;;;;;;lkOkkkkkOOkkkkkkxdddxkO0KXNNNWMMMMMMMWWMMMWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN00Kxcc:,..'';d0KKKXXXXXNNXXXXXXKKXXXXNWWWMMWWNXXXXXXXXNNNNXKXWXkc'...,xNWWNXKXWWMMMMMMMMMMMMWWWNXXKK000KKKXXXNNNNX0o,',;,,,,,,,,,,,,',,,,,,,,;;;;;;;;;;;;;;:okkkkkkkOOOOOOOOkkkOKNWWWWWWMMMMMMMMMMMMMMWNXNWWMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNK00dcc;'''''';d0XXXKXXXXXXXXXNNNNNXXXXXNNWWMMWWNNXKKKXKKKKKKXNNKd,..ckXWMWWWXXNWMMMMMMMMWWWWWWNXKKKKKKKXKXXXXNNNX0o,.',;,,,,,,,,,,,''',,,,,,,;;;;;;;;;;;::;:oOkkkOOOO0000OOOOkk0KNWMMWWMMMMMMMMMMMMMMMWNXXNWMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKOOdcc;'''','':xKXXKKXXXXXXXXNWWWWNNNXXXXNWWMMMWWWNXKKKKK0KXKXNNk;,o0WMWMMMWWNWWMMMWMMMMMWNNXXKKKKKXXXXXXXNNNNNNKo,..',,;;,,,,,,,,,''',,,,,,,,;;;;;;;;;;::;;oO0OOOOO000KKKKKK00KNNWWWWWMMMMMMMMMMMMMMMMWNKKNMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKOkocc;'.''''''cOXKKXXNNXXXXXNWWWMWWWNNXXXNNWWMWWMMWNXKKKKKKKKNNKO0NWMMMMMWWWWWWWWWWWWWWNXKKKKKXXXXXXXXXXNNNNNNKd,...',;;,,,,,,,,,''''',,,,,,,,;;;;;;;;;;;;,ckK0OOOO00KKKXXXXXXXKKKKNWMMMMMMMMMMMMMMMMMMWX0KNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKOxocc;,',,',,';d00KXXXNNNNNNNNWWMWWWWWWNNNNNNWWWWWWWWWNXKK00KKNNWWWWMWWMMMMMMWWNNWWWNXKKKKKKKXXXXXXNNNNNWWNXNXd,...',,,,,,,,,,,''''''',,,,,,,,,,;;;;;;,,;,,;lk0OOOO00000000OO00OOOO0XWMMMMMMMMMMMMMMMMMWNK0KWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdlcc:,,,',,;,,cx0KXXXNNNNNNNNWWWWWWWWWWWWNNNNWWWWWWWWWWWNXXNNWWWWWWWWWWMMMMMMWWWNNXKK000KKXXXXNNNNNWWWWNNXXKOc....,,'',,,,,,,''''''''',,,,,,,,,,;;;;,,;,,,.'lO0OOOO00OOOOOOOOOOOOOO0XWMMMMMMMMMMMMMMMMMMNKKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNOollc:,,,',,,,,,o0KKXNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMWMMMMWWMMMMMMMMMMWNXKK000KKKKXXXXNNNWWWWWNXXK0xc'..',;,',,,''''''''''''',,,,,,,,,,,,;,,,,,''..,oOK0OOOOOOOOOOOOOOOOOOOKNWMMMMMMMMMMMMMMMMMWNXXXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWW0oclc:,,,,,,,,,,ck0KXXNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMWWWNXKK000KKXXXXNNNNWWWWNXK0Oxo:..',;,,,,,'''''''''''''',,,,,,,,,,,,,,,''''.  ,d0K0kkO0000OOOOOOOOOOOKNWMMMMMMMMMMMMMMMMWWMWWNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0ollc:;,,,,,,,,,:dOKKKXXXNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMWMMMMMMMMMMMMMMMMWWWWWNXK000000KKKKKKKKKK0OOkkkxl'.',,,,,,''''''''''''''''',,,,,,,,,,,,''''..   'lOK0OOO00OOOOOOOOOOOOKXWMMMMMMMMMMMMMMMMMMWWMMWWNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMWKollc:;;;,,,,,,,,ckKK00KXNWWWWWWWWWWWWWMMMWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMWWWWWWWWWNXK0OOOO0OOOOOOOOOkkOO0Oo,.',',',,'''''''''..'''''''',,,,,,',,''''.....  .lkKK00OOOOOOOO00OOOO0XWMMMMMMMMMMMMMMMMMWWWWMMWNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWW0dlll:;;;,,;;;;;,:x0XK00KXNNWWWWWWWWWWWMMMMWWWWWWWWWMMMMWWWWMMMMMMMMWWMMMMMMMMWWWWWWWWWWWNXKKKKK00000000OOOOO0Od;'',,'',,''''''''....'''''''','''''''''''....   .,d0KK00OOOOOOO00O0OOOKNWMMMMMMMMMMMMMMMMWWWWMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWW0dlllc;;;,,;;:;;;;lkKXKKKKKXNWWWWWWWWWWWMMMWWWWWWWMMMMMMWWWWMMMMMMMMWWMMMMMMMMWWWWWWWWWWWWWNNNNXK000000OOOOOO00xc,,,,''''''''........''''''''''''''''......      .oOO00000OOO0000O0OOO0NWMMMMMMMMMMMMMMMWWMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWN0dllll:;;;;;:::::::dKXKKK000KXNWWWWWWWWWMMMMWMMMMWWWWMMWWNNWMMWWMMMMWWMMMMMMMMWWWWWWNNNNNWWWWNXKK000000OOOOOO0KOo;,,''...''...........''''''''''''''''..... ..   .ckOO0KKK0OOO000OOOOO0XWWMMMMMMWMMMMMMMWMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNOollolc;;;;:::::::;o0XKKKK000KXNWWWMMMWWWMMMMMMMMWWWWMMWNNNWMMWWMMMMMMMMMMMMMWWWWNNNNNNWWWWWNXK000000000OO000KK0d:,'''..................'''''''''''''.......     .,d0kxOKXK000OOO000000XNWWMMMMWWWWMMMMMMMMMMMMMMWNKKWMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMWMWNOdloolc:;;;::::::::lk00KKKK00KKXNNWWMMMMWWWWWMMMWWWMMMWWNNWMMMWWMMMMMMMMMMMWWWWWNNNNNNWWWWNXK0000000000000KKXXX0d;'.''..................'''''''''''''.......      .cOkddk0KXK00OO000000KNWWMMMWWWWWMMMMMMMMMMMMMMWNOx0NWMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMWMWXOdooolc:::::::::::ccok0KKKKK00KKXNNWMMMMMMWWWMMMMWWMMMWNNNWMMMWWMMMMMMMMMWWWWWNNNNXXNNWWWNK0OO000000000KKKXXXXXOc,''.''..................'''''''''''........      .:kkdooxOKXK000000000KXWWWWWWWWWWWMMMMMMMMMMMMMWWN0kOXWMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkdooolcc::::ccc:cccccd000KKKK0K0KXNWWMMMMMMMMMMMMMMMWWWWWWWMMMMWMMMMMMWWWWWWWNNNNXXXNNNXXK0O000000000KKKKXXXXKOo,....'''''................'''''''''........ ..     ;k0kdodxkOKKKK000000KXNNWWWWWWWWWMMMMMMMMMMMMMMWWWKkkKWWMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKkdooollc:::ccccccccccokO0KKKKK000KXNWWMMMMMMMMMWMMMWWNWWMMMWMMMMMMMMMMWWWWWWNNNNXXXXXXKK00000000000KKKKKKXKK0kc,.......'''.................''''''.............     'xK0kxxxxkO0KXK00000KXNNWWWWWWWWWWMWWWMMMMMMMWWWWWWN0kOXWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKkdoooolcc::cccccccllclok00KKK0000KKNWWWMMMMMMMMWMMMNNNWMMMMMMMMMMMMMMMWWWWWWNNXXXXXXKK000000000000KKKKKKKKK0d:'...........................''''''''............  .  .oOKKOkkxxkO0KKK0000KKXNNNWNNNWWWMWWWMMMMWWWMWMMWWWWWXOkKNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKkoooddolccccllccclllllldk0KKK0000KKXNWWWWMMMMMMMMMWNNNWMMMMMMMMMMMMMMWWWWNNNNXXXKKKKKK000000000000KKXKK0KK0d;............................'''''''''..........   ..  .;xKKK0OOkkOO0KKK0000KXXNNNNXNNWWMMMMMMMWWWWWWMMMWWWMMWKO0KNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKkdooddolccccllcclllllllldOKKKK00KKKXWWWWWWMMMMMMWWNNWWMMMMMMMMMMMMMWWWWWWNXXXXKKKKKKKK000000000000KXXKK00Od;.............................''''''''...........   .    .ckKXK000OOO00KKKK00KXXNNNNXXXNNWWWMMMMMWWWMMMMWWWWWWWWX00KNWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0xdoodddolcclllllllllolllox0KKKKKKKKXWWWWWWWMMMMWWNNWWMMMMMMMMMMWWWWWWWWWNNXKKKKKKKKKK000000000000KXXXKK0Od;..............................'''''''........ ...   ...   .;d0KKKK000KK000KKKKKXXNNNXXXXXXNWWMMMMMWWMMMWWNNNWWWWWWNXKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0xddddddolcllloolllooolllldk0KKKKKKKXNWWWWWWWMMWNNNWMMMMMMMWMMWWWWWWWWWWWWNXK000KKKK0000000000000KKXKK00Okc...............................''''''........  ...   ..  .   .ck0XK0000KKK0KKKKKXXXNXXXXKKXXNWWWWWWWWWMWWWNNNWMMMMMMWNXXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOxdddddddollllooooooooooooodkKKKKKXXXWWWWWWWWWWNNNWMMMWWMMMWWWWWWWWWWWWWWWNXKK0000000000000000000KKK0OOOxl,...............................'''''.........  .... ......  ...,lkKKK000KKKKKKKKKXXXXXXXXKKKXNNWWWWWWWWWNNWWWWWMMMMMMMWWNNNWWMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOddddddddolllloooolloddooooodOKKKKXXXNWWWWWWWNXXNWMMMMMMMMMWWWWWWWWWWWWWWWWNXK000000000000000000000OOkkko;................................'''''........   .........    .  ..;ok00000KKKKKKKKKXXXXXXXXKKKXXNNWWWWWWNNNNWMMWWMMMMMMMWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOxdddddxxdoooloddoooooooooddox0XXKKXXNNWWWWNXKXNWMMMWMMMMMMWWWWWWWNNNNWWWWWWNXK00000000000000KKK0OOkkkxd:...............  .................'''..........  .........       ...'lxO00KK000KKKKKXXXXXXXXKKKKKXNNWWWNNNXXNWMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0xdxxddxxddooooddoooooooodddodkKXXKXXNNWWWNXKXNWMMMMMMWWMMMMWWWWWNNNNNNWWWWWNXK00000000000000000OOkxxkxc'..............   ..........................  ..............        ..:oxkO000000KKKKXXXXXXKKKKKKKXNNNWWNNXXXNWMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0kxxxdxxxxddooodddddodddddddddxOKXKKXNNNWNXKXNWWWWWWWMMMMMMWWWWWNNNNNNNNNNNNNXK0000000000000OOOOkkkxxdl,................  ..........................  ..............       ....:oxdxkO000000KKXXXXXXKKKKKKXXXNWWNXXXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0Oxxxxxxxxxdoodddddddddddddxxddx0KKXXXNNNXKKXWWWWWWWWWWMMWWWWWWNNNNNNNNNNNNNNXKK00000000000OOkkkkkkxdc'............................................    .............          .'cdddxxkO0000KKKXXXXXKKKXXXXXXXNNXKKKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKOkxxxxxxxxddodddxdddddxxxxxxddxk0KXXNNXXKKXNWWWWWWWWWWMMWWWWWWNNNNXXXNNXXXXNXXK000000000OOOkkkkkOko;............................................     ..............        .  .'cdxxddxO0000KKKXKKKKKKXXXXXXXXKK00KNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKOkxxxxxxkxxdoddxxxdxxxxxxxxxxxxxOKKKXNXXKKXWWNNNWWNNNWWWWWWWWNNNNXXXXXXXKXXNXXKK000000OOOOOkOkkxxo;................................................................        ..  .,oddooddxkOO0KKXXXXXXXXXXXXXKK0000KNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXK0kxxxxxxkkxxdddxxxxxxxxxxxxxxxxxkOKKXXNNKKXWWNNNWWNNNWWWWWWWNNNNNXXXXXXXXXXXXKK00000OOOOkkOOOkxxd:.................................................................        .... .,ldoodddxxkO0KKXXXXXXXXXXXXK0OO0KXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNX0kxxxxxxxkkxxddxxxxxxxxxxxxxxkkkxk0XXXXNKKXWNNNWNNNXXNWWWWWWNNNNXXXXXXXXXXKKK0000OOOOOOOkkOOOkxdo;. ........................................     ..      ...........      .....  .;odoodoodxkOO0KKKXXXXXXXXK00000XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWN0kxxkkkxxkkkxxxxxxxxxxxxkkkkkkkkkkO0KXXK00XWNNNNNNXXXNWWWWWWNNNXXXXXXXXKKKK000000OOOOO0OOOkkxxxd:........................ ...................     ..      ..........       ...... .;dxdoddddddxkO00KKXXXXXK0000KKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWNKkkkkkkkkkkkkkxxxxxkkkkkkkkkkkkkkkkOKXXKOOXWNXNNNXXKXNWWWWWWNNXXXKKKKKKKKK0000OOOOOOOOOOOOkkxxko,..............................................   ...     ..........      .   ..   .:oxddddoooddxkOO00KKKK00000KNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMWNWWWKOkkkkkkkkkOOOkxxxkkkkkkkkkkkkkOOkkO0KK0kkXWXXXXXXKKXNWWWWWNNNXXKKKKKKK0000000OOOOOOOOOOOOkkkkdc. ..............................................  ...    ...........    .........   ..;lodddddooodxxkkO00000000XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMWWWWMWXOkkkOOkkkkO0OkxkkkkkkkkkkkkOOOOOOkk0KK0xkXNXXXKKKK0KNWWWWWNNXXXKKKKK0000000000OOOOOOOO00Okxxxl,.......  .............................. ........  .... ..............   ........       .,;:clododdxxddxkOOOOOKXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMWWNWMMWXkxkOOOkkkkO00OxkkkkkkkkkOOOOOOOOOOOO00OxkXNXKKKKK00KXWWWWWNNXXKKKK00000000000000O00000K0Okxxd;........  .............................  ............................     .......        ..',:lllok000Okk0KXXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMWNXNWMMXOkkkOOOOkkO0XKOkkOOOkOOOOOOOOOOOO0OO00OxkKNKKKKKKK0KXNWWWNNXKKKKKK00000000000000000000K0Okxdc'..........................   ........................................     ..........      ..,:cllxKNWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMWNNWWMMNOkkkkOOOOOO0KX0kkOO0OOOOOOOOOOOOO0OO000OOKXKKKKKKK0KKNWWWNXXKKKKKK0000000000000000KK0000Okko'........................... ..........................................     ..........       .';ccokXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMWNWWMMMMN0OOkOOOOOOOOKNKOkkO00OOOOOOOOOOOO0000000O0KKKKKKK000KXNNNNXKKKKKK00000000000000000KK0000Oxd:.  ....................................................................     ..........        .':coONWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMWNNWMMMMMWK0OkOOOOOO0O0XNKOkO000OOOOOOO00OO000000000KKKKK00000KXXNNXXKK0KKK00000000000000000KK000OOd:........................................................................     ...........        .:lo0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMWWWWWWMMMMMWNKOOOOOOOOOOOKNNK0OO0K00OOOO00000000000000KXKK0000000KXXXXKK00000000000000000000000000OOxc..... ...................................................................    .............       .;lxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMWWWWWMWWMWWWWXOO00OOOOOOO0NWXKOO0KKK0OO00000000KK00000KXXK0000000KKXXXKK0000000000000000000000000OOkl.... .....................................................................    .............   .    ,lOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMWWNNWWWWMMMMWX0OO0OOO0OOO0KNWX0OO0KK00000000000K000000KKKKK00O00000KKK0000000000000KKKKKKK0000000Oxc.  .  .......................................................................  ............... ..   'oKWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMWWWWWWWMMMMWNKOOO0OO000000XWNX0O00KKK00000000000000000KKKKK000000000000000000000000KKKKKKKKK000Od:.  ..  .........................................................................................    .'oXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMWWWWWWWWWWMMMMMWX0OO000000000XWWNK0000KKK00000000000000000KXKKK000OO0000000000000KKK000KKKK000000kc'...................................................................................................  .'dNMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMNKOO000000000KNWWNK0O00KKK00K00000000000000KKKK000OOOOOOOO0000000KKK000KKK000K0kl'.....................................................................................................  .,xNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMWWWWMMMMMMMMMMMMWX00000000000KXNWWNK000KKKKKKKKKKKKKK0KKKK00KKKK0O00OOOOOOOO000000KK00KK000K0xc'.. ..................................................................................................    .,xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMWWWWWMMMMMMMMMMMMMWWWNX00000000000KXNWWNXK00KKKKKKKKKKKKKKKKKKK000KKK0OOOOOOOOOOOOOOO000000000Od:'.      ................................................................................................    ..cKWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMWNK0K000KKK00KKXWWWNXKKKKKKXKKKKKKKKKKKKKKK000KKK00OOOOOOOOOOOOOOOOOOOOOd:..        ................................................................................................    ...l0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXK0000KKKKKKKXNWMWWXKKKKKXXKKKKKKKKKKKKXKKKKKKK000OkkOOOOOOkkkkkO00kl,..   ...  ..................................................................................................  ......'dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNX000KK0KKKKKKXNWMWNXKKKKKXXXKKKKKKKXXXKKKKKXK00KK0OOOOOOOOOOkkkOxc'.        .....................................................................................................  .....  'xXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXK000KKKKKKKKXNWMWWXKKKKKXXXXKKKKKXXXXKKKKKKKKKK00K0OxxkkOkkxo:'.         ......................................................................................................  .....  .l0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXK0KKKKKKKKKXXNWWMWNXKKKKXXNXXKKKXXXKXXKKKKXXKKKXX0x:,;:::;;'..       .......................................................................................................... .....  .c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKKKKKKKKKKKXNWWMWWNXKKKKXNNNXXXXXKKXXXXXXXXXXXXXKx;';:;,'.....    ................................................................................................................... .cOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXXKKKKKKKKXXXNWWWWWNXKKKXXNNNNXKKXXXXXXXXXXXXXXXXO:';;,'..      ..... .............................................................................................................   .c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKKKKKKXXXKXNWWMMWWNKKXXXXNWNXXXXXXXXXXXXXXXXXXk:',,...        .................................................................................................................    .l0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXXKKKXXXXKXNWMMMMWNXKKKXXNNWWWNNNXXXXXXXXXXN0d,.'..         .................................................................................................................  .. .oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMWNXXKKXXXXXXNWWMMWWWNXKXXXNNWMWWNNNNXXXXXXNXkc'...   ..     ................................................................................................................ ...  .dXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXXKXXXXXXNWWWWMMWNNXXXXNNWWWWWWWWNNNXXKkl;'..   ..     ...............................................................................................................   ..   .xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKXXXXXXNWWMMMWWWNXXNNNNNWWMMWWWWNNN0l;,..    .    ................................................................................................................         ,OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXXXKXXXXNWMMMWWWWNNXXXXXNWWMMWWWWWWKo:;.  ...... .....................................................................................................................    .:KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNNNXXXXNWWWWWMMWWWNNXXNNNWWWWMMMMNOl,..     .......................................................................................................................    .;xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNXXNNNWWWMMMMMWWNNNNNNNWWMMMMWXx;...    .....................................................................................................................    .'cONWMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNNNNNWWWMMMMMWWWWNXXXNNWMMMMMNk:....   ....................................................................................................................    ..l0WMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
        int freq1 = 0;

        // res to store the most occurring string in the array of
        // strings
        String res1 = "";

        // running nested for loops to find the most occurring
        // word in the array of strings
        for (int i = 0; i < prefixes.size(); i++) {
            int count = 0;
            for (int j = i + 1; j < prefixes.size(); j++) {
                if (prefixes.get(j).equals(prefixes.get(i))) {
                    count++;
                }
            }

            // updating our max freq of occurred string in the
            // array of strings
            if (count >= freq1) {
                res1 = prefixes.get(i);
                freq1 = count;
            }
        }
        int freq2 = 0;

        // res to store the most occurring string in the array of
        // strings
        String res2 = "";

        // running nested for loops to find the most occurring
        // word in the array of strings
        for (int i = 0; i < suffixes.size(); i++) {
            int count = 0;
            for (int j = i + 1; j < suffixes.size(); j++) {
                if (suffixes.get(j).equals(suffixes.get(i))) {
                    count++;
                }
            }

            // updating our max freq of occurred string in the
            // array of strings
            if (count >= freq2) {
                res2 = suffixes.get(i);
                freq2 = count;
            }
        }
        System.out.println(words.size() + " total SubWords");

        System.out.println("The prefix that occurs most is : " + res1);
        System.out.println("No of times: " + freq1);

        System.out.println("The suffix that occurs most is : " + res2);
        System.out.println("No of times: " + freq2);


        //System.out.println("no one says the prefix and suffix finders have to be efficient go screw yourself");
        System.out.println("*end of program*");
    }

}
